Repository COBREXA/ConstraintTrees.jl, pull requests merged in 2023-12, with the labels that each got.

#15 make the bounds type open to extension
  Project.toml
  docs/src/metabolic-modeling.jl
  docs/src/quadratic-optimization.jl
  src/bound.jl
  src/constraint.jl
  src/constraint_tree.jl
  test/misc.jl
Labels: enhancement, :black_heart: may unhex MILPs :black_heart:

#14 Add ability to constraint variables to binary or integer values.
  Project.toml
  docs/Project.toml
  docs/src/1-metabolic-modeling.jl
  docs/src/2-quadratic-optimization.jl
  docs/src/3-mixed-integer-optimization.jl
  test/runtests.jl
Labels: documentation, enhancement, :magic_wand: hexed by MILPs :magic_wand:

#19 generalize tree_map to all types
  Project.toml
  src/tree.jl
Labels: bug
